var Set = require('./setFunc')
var cis = new Set()
cis.add('Mike')
cis.add('Clayton')
cis.add('Jennifer')
cis.add('Raymond')

var dmp = new Set()
dmp.add('Raymond')
dmp.add('Cynthia')
dmp.add('Jonathan')

var it = new Set()
it = cis.union(dmp)
console.log('union set', it.show())